### ISSUE TITLE
Missing a source count to milk bucket

### ISSUE THREAD

**Issue by SuperCameleon** [ElitoGame/mcdle-public#10]
In 1.20, milk bucket can be obtain in two ways (interaction and mob loot from wandering trader, if we kill him while he drinks it), but in 1.21 we can now obtain in chest findable in trial chamber. But currently, only two sources are indicated (the same as in 1.20).

**Comment by ElitoGame** [comment]
Thanks will be live tomorrow! Also cool detail with the wandering trader milk bucket, did not know about that, I don't read all the wiki pages, but always curious what you learn about the game!
