### ISSUE TITLE
Add translation for "armor_trim_smithing_template"

### ISSUE THREAD

**Issue by Juloos** [ElitoGame/mcdle-public#9]
Missing translation keys for "armor_trim_smithing_template".
It is only present in the french translation, which makes all the other languages fallback to the french name on the website.

**Comment by ElitoGame** [comment]
Will fix it with the 1.21 update next week ^^

**Comment by ElitoGame** [comment]
This has been fixed in [#6ecb08252eecf58b44f9dfadd0e48653dac69bdc](https://github.com/ElitoGame/mcdle-public/commit/6ecb08252eecf58b44f9dfadd0e48653dac69bdc)
